#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/capri

PRODUCT_PACKAGES += \
    CarrierConfigOverlay

PRODUCT_COPY_FILES += \
    vendor/motorola/capri/proprietary/product/etc/CarrierSettings/carrier_list.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/carrier_list.pb \
    vendor/motorola/capri/proprietary/product/etc/CarrierSettings/others.pb:$(TARGET_COPY_OUT_PRODUCT)/etc/CarrierSettings/others.pb

PRODUCT_COPY_FILES += \
    vendor/motorola/capri/proprietary/recovery/root/vendor/firmware/ILITEK_FW_TM_9882N:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/ILITEK_FW_TM_9882N \
    vendor/motorola/capri/proprietary/recovery/root/vendor/firmware/ILITEK_FW_TXD_7806S:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/ILITEK_FW_TXD_7806S \
    vendor/motorola/capri/proprietary/recovery/root/vendor/firmware/ILITEK_FW_TXD_9882H:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/ILITEK_FW_TXD_9882H \
    vendor/motorola/capri/proprietary/recovery/root/vendor/firmware/djn_novatek_ts_fw.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/djn_novatek_ts_fw.bin \
    vendor/motorola/capri/proprietary/recovery/root/vendor/firmware/djn_novatek_ts_mp.bin:$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware/djn_novatek_ts_mp.bin \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.2.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.2.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/power/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/power/Bluetooth_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/power/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/power/General_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/power/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/power/Global_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/power/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/power/Handset_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/power/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/power/Hdmi_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/power/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/power/Headset_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/acdbdata/power/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/power/Speaker_cal.acdb \
    vendor/motorola/capri/proprietary/vendor/etc/camera/aec_golden_depth.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/aec_golden_depth.bin \
    vendor/motorola/capri/proprietary/vendor/etc/camera/aec_golden_ov8856_wide.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/aec_golden_ov8856_wide.bin \
    vendor/motorola/capri/proprietary/vendor/etc/camera/aec_golden_wide.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/aec_golden_wide.bin \
    vendor/motorola/capri/proprietary/vendor/etc/camera/arcsoft_calibration_u_dc.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/arcsoft_calibration_u_dc.bin \
    vendor/motorola/capri/proprietary/vendor/etc/camera/dc_mot_ov8856.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dc_mot_ov8856.bin \
    vendor/motorola/capri/proprietary/vendor/etc/camera/dual_golden_depth.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dual_golden_depth.bin \
    vendor/motorola/capri/proprietary/vendor/etc/camera/dual_golden_ov8856_wide.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dual_golden_ov8856_wide.bin \
    vendor/motorola/capri/proprietary/vendor/etc/camera/dual_golden_wide.bin:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dual_golden_wide.bin \
    vendor/motorola/capri/proprietary/vendor/etc/camera/vidhance_calibration:$(TARGET_COPY_OUT_VENDOR)/etc/camera/vidhance_calibration \
    vendor/motorola/capri/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-chipone2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-chipone2.rc \
    vendor/motorola/capri/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service-fpc2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service-fpc2.rc \
    vendor/motorola/capri/proprietary/vendor/etc/init/android.hardware.nfc@1.2-service-moto.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.nfc@1.2-service-moto.rc \
    vendor/motorola/capri/proprietary/vendor/etc/init/init_thermal-engine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine.rc \
    vendor/motorola/capri/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/motorola/capri/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/motorola/capri/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_djn_nt36525b_652.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_djn_nt36525b_652.xml \
    vendor/motorola/capri/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_tm_ili9882n_652.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_tm_ili9882n_652.xml \
    vendor/motorola/capri/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_txd_ili7806s_652.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_txd_ili7806s_652.xml \
    vendor/motorola/capri/proprietary/vendor/etc/qdcm_calib_data_mipi_mot_vid_txd_ili9882h_652.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_mipi_mot_vid_txd_ili9882h_652.xml \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_default_sensors.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_dynamic_sensors.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_icm4x6xx_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_lis2doc_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_lis2doc_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_lsm6dso_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_mn78xxx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_mn78xxx_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_power_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_sc7a20_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_sc7a20_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_stk3a5x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_stk3a5x_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_stk8baxx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_stk8baxx_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_vcnl36866_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_vcnl36866_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/bengal_vcnl36866_0_always.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bengal_vcnl36866_0_always.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icm4x6xx_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/mot_camgest.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_camgest.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/mot_chopchop.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_chopchop.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/mot_devorient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_devorient.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/mot_drop.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_drop.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/mot_ltv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_ltv.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/mot_offbody.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/mot_offbody.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sc7a20_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sc7a20_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_walk.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_walk.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/stk3a5x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/stk3a5x_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/stk8baxx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/stk8baxx_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/config/vcnl36866_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/vcnl36866_0.json \
    vendor/motorola/capri/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/motorola/capri/proprietary/vendor/etc/thermal-engine-capri-5000.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-capri-5000.conf \
    vendor/motorola/capri/proprietary/vendor/etc/thermal-engine-capri-6000.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine-capri-6000.conf \
    vendor/motorola/capri/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/motorola/capri/proprietary/vendor/etc/vhw.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vhw.xml \
    vendor/motorola/capri/proprietary/vendor/firmware/ILITEK_FW_TM_9882N:$(TARGET_COPY_OUT_VENDOR)/firmware/ILITEK_FW_TM_9882N \
    vendor/motorola/capri/proprietary/vendor/firmware/ILITEK_FW_TXD_7806S:$(TARGET_COPY_OUT_VENDOR)/firmware/ILITEK_FW_TXD_7806S \
    vendor/motorola/capri/proprietary/vendor/firmware/ILITEK_FW_TXD_9882H:$(TARGET_COPY_OUT_VENDOR)/firmware/ILITEK_FW_TXD_9882H \
    vendor/motorola/capri/proprietary/vendor/firmware/NT36xxx_MP_Setting_Criteria_601D.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/NT36xxx_MP_Setting_Criteria_601D.csv \
    vendor/motorola/capri/proprietary/vendor/firmware/NT36xxx_MP_Setting_Criteria_602B.csv:$(TARGET_COPY_OUT_VENDOR)/firmware/NT36xxx_MP_Setting_Criteria_602B.csv \
    vendor/motorola/capri/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/motorola/capri/proprietary/vendor/firmware/aw882xx_mono.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_mono.bin \
    vendor/motorola/capri/proprietary/vendor/firmware/aw882xx_mono_power.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_mono_power.bin \
    vendor/motorola/capri/proprietary/vendor/firmware/aw882xx_spk_reg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw882xx_spk_reg.bin \
    vendor/motorola/capri/proprietary/vendor/firmware/djn_novatek_ts_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/djn_novatek_ts_fw.bin \
    vendor/motorola/capri/proprietary/vendor/firmware/djn_novatek_ts_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/djn_novatek_ts_mp.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_capri_gc02m1_union.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_capri_gc02m1_union.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_capri_ov02b10_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_capri_ov02b10_ofilm.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_capri_ov02b1b.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_capri_ov02b1b.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_capri_ov8856_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_capri_ov8856_ofilm.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_capri_s5k4h7_front_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_capri_s5k4h7_front_ofilm.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_capri_s5k4h7_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_capri_s5k4h7_ofilm.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.sensormodule.mot_capri_s5kgm1st_ofilm.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.mot_capri_s5kgm1st_ofilm.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.tuned.mot_capri_gc02m1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_capri_gc02m1.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.tuned.mot_capri_ov02b10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_capri_ov02b10.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.tuned.mot_capri_ov02b1b.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_capri_ov02b1b.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.tuned.mot_capri_ov8856.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_capri_ov8856.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.tuned.mot_capri_s5k4h7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_capri_s5k4h7.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.tuned.mot_capri_s5k4h7_front.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_capri_s5k4h7_front.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/com.qti.tuned.mot_capri_s5kgm1st.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.mot_capri_s5kgm1st.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/motorola/capri/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/motorola/capri/proprietary/vendor/usr/idc/uinput-fpc.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/uinput-fpc.idc \
    vendor/motorola/capri/proprietary/vendor/usr/idc/uinput-fpsensor.idc:$(TARGET_COPY_OUT_VENDOR)/usr/idc/uinput-fpsensor.idc \
    vendor/motorola/capri/proprietary/vendor/usr/keylayout/uinput-fpc.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/uinput-fpc.kl \
    vendor/motorola/capri/proprietary/vendor/usr/keylayout/uinput-fpsensor.kl:$(TARGET_COPY_OUT_VENDOR)/usr/keylayout/uinput-fpsensor.kl

PRODUCT_PACKAGES += \
    libthermalclient \
    com.mot.eeprom.mot_capri_s5k4h7_front_otp \
    com.mot.eeprom.mot_capri_s5k4h7_otp \
    com.mot.eeprom.mot_dw9767_s5kgm1st_actuator \
    com.mot.eeprom.mot_gt24p64e_ov8856_eeprom \
    com.mot.eeprom.mot_ov02b1b_otp \
    com.qti.sensor.mot_capri_s5k4h7 \
    com.qti.sensor.mot_capri_s5k4h7_front \
    com.qti.sensor.mot_gc02m1 \
    com.qti.sensor.mot_ov02b10 \
    com.qti.sensor.mot_ov02b1b \
    com.qti.sensor.mot_ov8856 \
    com.qti.sensor.mot_s5kgm1st \
    com.arcsoft.node.dc_capture \
    com.arcsoft.node.dc_preview \
    com.arcsoft.node.smooth_transition \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swcac \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.vidhance.node.processing \
    com.vidhance.stats.aec_dmbr \
    com.fingerprints.extension@1.0 \
    com.qti.chiusecaseselector \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs \
    com.qti.feature2.hdr \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.rt \
    com.qti.feature2.serializer \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    camera.qcom \
    chipone.fingerprint.default \
    com.qti.chi.override \
    libarcsoft_distortion_correction \
    libarcsoft_dual_sat \
    libarcsoft_dual_zoomtranslator \
    libarcsoft_portrait_distortion_correction \
    libbitmlengine \
    libcamera_nn_stub \
    libcamerapostproc \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxncs \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchilog \
    libcom.qti.chinodeutils \
    libfcell \
    libfp_ext_svc2 \
    libipebpsstriping \
    libjpege \
    liblmutils-ns \
    liblowlight_ai_portrait.arcsoft \
    libmctfengine_stub \
    libmmcamera_cac3 \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmot_afd \
    libmot_lux_standardization \
    libmpbase \
    libmulticam_optical_zoom_control \
    libmulticam_video_optical_zoom \
    libofflinelog \
    libopencv \
    libopestriping \
    libpn557_fw \
    libswregistrationalgo \
    libtfestriping \
    libvidhance \
    libvidhance_active_ois \
    libvidhance_dmbr \
    libvidhance_face_stabilizer \
    libvidhance_fbc \
    libvidhance_horizon_correction \
    libvidhance_stabilizer \
    vendor.fpsensor.hardware.fpsensorhidlsvc@2.0 \
    capsense_reset \
    cnss-daemon \
    android.hardware.biometrics.fingerprint@2.1-service-chipone \
    android.hardware.biometrics.fingerprint@2.1-service-fpc \
    fpc_ident \
    thermal-engine
